## Project-wide Gradle settings.
#
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
APP_VERSION_CODE=7038
APP_VERSION_NAME=12.10.1
APP_PACKAGE=org.justgram.messenger
IS_PRIVATE=false
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.vfs.watch=true
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1536m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:SoftRefLRUPolicyMSPerMB=1 -Dfile.encoding=UTF-8
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.parallel.tasks.in.project=true
kotlin.daemon.jvmargs=-Xmx3g -XX:+UseG1GC
android.useAndroidX=true
android.enableJetifier=false
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false
android.enableR8.fullMode=true
